# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "courses-terraform-terragrunt-states-bucket"
    dynamodb_table = "courses-lock-table"
    encrypt        = false
    key            = "ap-northeast-1/kms_key/terraform.tfvars"
    profile        = "stadleTerraform"
    region         = "ap-northeast-1"
  }
}
